### ISSUE TITLE
Mixed-content warnings on demo page

### ISSUE THREAD

**Issue by qgustavor** [asvd/intence#5]
From developer console messages seems it's caused by fonts, which don't get loaded. Also would be better updating all protocols in the page to HTTPS where possible.

**Comment by asvd** [comment]
Does it happen all the time? Cuz I cannot reproduce it currently...

Which browser do you use?

NB on https: it's a cool trend currently, but not needed for intence homepage: it's just a read-only page with no opportunity to send the data from a user to the server imho.

**Comment by asvd** [comment]
Now I see, the message appears when you open the page with https, right? Did you manually replace the protocol in your addres bar or followed a link from somewhere?

**Comment by qgustavor** [comment]
HTTPS Anywhere activated: because it sometimes I forgot those GitHub Pages
also work on HTTP.

Some points about your comply against HTTPS: don't say that, even if you're
not sending sensitive data please, use HTTPS. There are many reasons for
that, read some in this page:
https://security.stackexchange.com/questions/38832/should-a-site-have-ssl-if-it-doesnt-have-a-login-form
Also don't forget that HTTPS will be too cheap and easy to implement (like
with https://letsencrypt.org/ or CloudFlare) that there is a high chance
browsers will mark HTTP as insecure in future (Chrome already implements
something like that under a flag).

I will send a PR fixing it.
